import type { BoardDef } from "./boards";
import type { SampleId } from "./samples";
import { SAMPLES } from "./samples";
import type { CredentialInfo } from "../credentialExport";

export interface GenerateSketchInput {
  board: BoardDef;
  sample: SampleId;
  device: CredentialInfo;
  mqttHost: string;
}

function sanitizeForComment(s: string): string {
  return s.replace(/\*\//g, "* /").replace(/[\r\n]+/g, " ");
}

function requiredLibraries(sample: SampleId): string {
  const base = '    - "PubSubClient" by Nick O\'Leary';
  if (sample === "dht11") {
    return [
      base,
      '    - "DHT sensor library" by Adafruit',
      '    - "Adafruit Unified Sensor" by Adafruit',
    ].join("\n");
  }
  return base;
}

function heartbeatNote(board: BoardDef): string {
  if (board.id !== "esp32-c3-supermini") return "";
  return `
  // NOTE: some ESP32-C3 SuperMini clones wire the onboard LED the
  // opposite way round depending on the seller/batch. If it stays lit
  // while "off" and dark while blinking, swap HEARTBEAT_LED_ON/OFF below.`;
}

function sampleGlobals(sample: SampleId, board: BoardDef): string {
  if (sample === "relay") {
    return `
#define RELAY_PIN ${board.defaultGpio}
#define RELAY_ACTIVE_LOW false // set true if your relay module triggers on LOW
#define RELAY_TARGET_NAME "relay_1" // must match "Target" in the dashboard's "Send a command" form
bool relayState = false;`;
  }
  if (sample === "dht11") {
    return `
// Wiring: DHT11 data pin -> DHT_PIN, VCC -> 3.3V, GND -> GND.
// If your DHT11 module has no built-in pull-up, add a 10k resistor
// between the data pin and 3.3V.
#define DHT_PIN ${board.defaultGpio}
#define DHT_TYPE DHT11
DHT dht(DHT_PIN, DHT_TYPE);
const unsigned long TELEMETRY_INTERVAL_MS = 10000;
unsigned long lastTelemetry = 0;`;
  }
  return "";
}

function sampleSetupExtra(sample: SampleId): string {
  if (sample === "relay") {
    return `  pinMode(RELAY_PIN, OUTPUT);
  digitalWrite(RELAY_PIN, RELAY_ACTIVE_LOW ? HIGH : LOW);
`;
  }
  if (sample === "dht11") {
    return `  dht.begin();
`;
  }
  return "";
}

function sampleCallback(sample: SampleId): string {
  if (sample !== "relay") return "";
  return `
void applyRelay(bool on) {
  relayState = on;
  bool pinHigh = RELAY_ACTIVE_LOW ? !on : on;
  digitalWrite(RELAY_PIN, pinHigh ? HIGH : LOW);
  char payload[64];
  snprintf(payload, sizeof(payload), "{\\"target\\":\\"%s\\",\\"state\\":%s}", RELAY_TARGET_NAME, on ? "true" : "false");
  mqtt.publish(TOPIC_STATUS, payload);
  Serial.println(payload);
}

void mqttCallback(char* topic, byte* payload, unsigned int length) {
  String body;
  body.reserve(length);
  for (unsigned int i = 0; i < length; i++) body += (char)payload[i];
  Serial.print("Received on ");
  Serial.print(topic);
  Serial.print(": ");
  Serial.println(body);

  // Expected payload (exactly what the dashboard's "Send a command" form
  // sends): {"target":"relay_1","command":"set","value":true}
  // A tiny hand-rolled check is used here to avoid pulling in a JSON
  // library for one field — swap in ArduinoJson if you need more.
  if (body.indexOf("\\"target\\":\\"" RELAY_TARGET_NAME "\\"") == -1) return;
  if (body.indexOf("\\"command\\":\\"set\\"") == -1) return;
  applyRelay(body.indexOf("\\"value\\":true") != -1);
}
`;
}

function sampleLoopBody(sample: SampleId): string {
  if (sample === "blink") {
    return `
  // ---- Sample: periodic "still alive" ping over MQTT ----
  // The LED above already blinks locally; this additionally proves the
  // full WiFi + MQTT path works end-to-end. Watch it appear under
  // "Recent messages" on this device's page in the dashboard.
  static unsigned long lastPing = 0;
  if (millis() - lastPing >= 5000) {
    lastPing = millis();
    mqtt.publish(TOPIC_PING, "{}");
    Serial.println("Published ping");
  }
`;
  }
  if (sample === "dht11") {
    return `
  // ---- Sample: read DHT11 and publish telemetry ----
  if (millis() - lastTelemetry >= TELEMETRY_INTERVAL_MS) {
    lastTelemetry = millis();
    float humidity = dht.readHumidity();
    float tempC = dht.readTemperature();
    if (isnan(humidity) || isnan(tempC)) {
      Serial.println("DHT11 read failed - check wiring/pin.");
    } else {
      char payload[96];
      snprintf(payload, sizeof(payload), "{\\"temperature_c\\":%.1f,\\"humidity_pct\\":%.1f}", tempC, humidity);
      mqtt.publish(TOPIC_TELEMETRY, payload);
      Serial.println(payload);
    }
  }
`;
  }
  // relay: state changes are driven entirely by the mqtt callback via mqtt.loop()
  return "";
}

export function generateSketch({ board, sample, device, mqttHost }: GenerateSketchInput): string {
  const sampleDef = SAMPLES.find((s) => s.id === sample)!;
  const clientId = device.clientId;
  const isRelay = sample === "relay";

  return `/*
  Generated by the IoTStack dashboard
  Sample: ${sampleDef.title}
  Board:  ${board.label}
  Device: ${sanitizeForComment(device.displayName)} (client_id: ${clientId})
  Generated: ${new Date().toISOString()}

  ------------------------------------------------------------------
  REQUIRED LIBRARIES (Arduino IDE > Tools > Manage Libraries):
${requiredLibraries(sample)}
  ------------------------------------------------------------------
  BEFORE UPLOADING:
    1. Fill in your WiFi SSID and password below.
    2. MQTT_HOST defaults to the address this dashboard was open at
       (${mqttHost}) when this file was generated. Change it if this
       device will reach the broker through a different address.
    3. Client ID / username / password below are already filled in for
       THIS device - don't reuse them on another device.
  ------------------------------------------------------------------
*/

#include <WiFi.h>
#include <PubSubClient.h>
${sample === "dht11" ? "#include <DHT.h>\n" : ""}
// ---- WiFi ----
const char* WIFI_SSID = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

// ---- MQTT broker ----
const char* MQTT_HOST = "${mqttHost}";
const uint16_t MQTT_PORT = 1883; // plain MQTT (see IoTStack README for TLS/WebSocket ports)

// ---- Device credentials (generated for this device - keep private) ----
const char* MQTT_CLIENT_ID = "${clientId}";
const char* MQTT_USERNAME  = "${device.mqttUsername}";
const char* MQTT_PASSWORD  = "${device.password}";

// ---- Topics ----
const char* TOPIC_TELEMETRY = "devices/${clientId}/telemetry";
const char* TOPIC_CMD       = "devices/${clientId}/cmd";
const char* TOPIC_STATUS    = "devices/${clientId}/status";
const char* TOPIC_PING      = "devices/${clientId}/ping";

// ---- Heartbeat LED (present on every generated sketch) ----
// Blinks the onboard LED once a second so you can tell at a glance the
// board is powered and the main loop is running, even without opening
// Serial Monitor (it will freeze here if setup() gets stuck, e.g. bad
// WiFi credentials).
#define HEARTBEAT_LED_PIN ${board.ledPin}
#define HEARTBEAT_LED_ON  ${board.ledActiveLow ? "LOW" : "HIGH"}
#define HEARTBEAT_LED_OFF ${board.ledActiveLow ? "HIGH" : "LOW"}${heartbeatNote(board)}
const unsigned long HEARTBEAT_INTERVAL_MS = 1000;
unsigned long heartbeatLastToggle = 0;
bool heartbeatLedOn = false;

WiFiClient wifiClient;
PubSubClient mqtt(wifiClient);
${sampleGlobals(sample, board)}

void connectWiFi() {
  Serial.print("Connecting to WiFi \\"");
  Serial.print(WIFI_SSID);
  Serial.println("\\"...");
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) {
    delay(300);
    Serial.print(".");
  }
  Serial.print("\\nWiFi connected, IP: ");
  Serial.println(WiFi.localIP());
}
${sampleCallback(sample)}
void reconnectMQTT() {
  while (!mqtt.connected()) {
    Serial.print("Connecting to MQTT broker ");
    Serial.print(MQTT_HOST);
    Serial.print(":");
    Serial.print(MQTT_PORT);
    Serial.println("...");
    if (mqtt.connect(MQTT_CLIENT_ID, MQTT_USERNAME, MQTT_PASSWORD)) {
      Serial.println("MQTT connected.");
${isRelay ? "      mqtt.subscribe(TOPIC_CMD);\n" : ""}      mqtt.publish(TOPIC_PING, "{\\"event\\":\\"boot\\"}");
    } else {
      Serial.print("MQTT connect failed, rc=");
      Serial.print(mqtt.state());
      Serial.println(" - retrying in 2s");
      delay(2000);
    }
  }
}

// Non-blocking: toggles the LED by timestamp instead of delay(), so it
// keeps blinking evenly while WiFi/MQTT work happens in the same loop().
void updateHeartbeat() {
  unsigned long now = millis();
  if (now - heartbeatLastToggle >= HEARTBEAT_INTERVAL_MS) {
    heartbeatLastToggle = now;
    heartbeatLedOn = !heartbeatLedOn;
    digitalWrite(HEARTBEAT_LED_PIN, heartbeatLedOn ? HEARTBEAT_LED_ON : HEARTBEAT_LED_OFF);
  }
}

void setup() {
  Serial.begin(115200);
  pinMode(HEARTBEAT_LED_PIN, OUTPUT);
  digitalWrite(HEARTBEAT_LED_PIN, HEARTBEAT_LED_OFF);

${sampleSetupExtra(sample)}  connectWiFi();
  mqtt.setServer(MQTT_HOST, MQTT_PORT);
${isRelay ? "  mqtt.setCallback(mqttCallback);\n" : ""}  reconnectMQTT();
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) connectWiFi();
  if (!mqtt.connected()) reconnectMQTT();
  mqtt.loop();

  updateHeartbeat();
${sampleLoopBody(sample)}}
`;
}
